set_property PACKAGE_PIN U4 [get_ports {qsfp1_rx_p[3]}]
set_property PACKAGE_PIN V2 [get_ports {qsfp1_rx_p[2]}]
set_property PACKAGE_PIN W4 [get_ports {qsfp1_rx_p[1]}]
set_property PACKAGE_PIN Y2 [get_ports {qsfp1_rx_p[0]}]
set_property PACKAGE_PIN AY24 [get_ports clk125mhz_p]
set_property PACKAGE_PIN W9 [get_ports qsfp1_refclk_p]

create_clock -period 8.000 -name clk125mhz_p -waveform {0.000 4.000} [get_ports clk125mhz_p]
create_clock -period 6.400 -name qsfp1_refclk_p -waveform {0.000 3.200} [get_ports qsfp1_refclk_p]

set_property IOSTANDARD LVDS [get_ports clk125mhz_p]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_125mhz_BUFG]
